version: "3"

services:
  mongo:
    image: mongo
    restart: always
    container_name: api_db
    volumes:
    - ./data:/data/db

  api:
    build: ./
    container_name: api
    ports:
      - 5001:5000
    restart: always
    depends_on:
      - mongo