version: "3"

services:
  mongo:
    image: mongo
    restart: always
    container_name: api_db

  api:
    build: ./
    container_name: api
    ports:
      - 5000:5000
    restart: always
    depends_on:
      - mongo